[build]
builder = "nixpacks"
buildCommand = "cd be && npm ci && npm run build"

[deploy]
startCommand = "node start.js"
# healthcheckPath = "/health"
# healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
