global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Auth Service metrics
  - job_name: 'auth-service'
    static_configs:
      - targets: ['kong-gateway:8000']
    metrics_path: '/auth/metrics'
    scrape_interval: 5s

  # Morse Service metrics
  - job_name: 'morse-service'
    static_configs:
      - targets: ['kong-gateway:8000']
    metrics_path: '/morse/metrics'
    scrape_interval: 5s

  # Kong metrics (if enabled)
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
